apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "babilcors.fullname" . }}-config
  labels:
    {{- include "babilcors.labels" . | nindent 4 }}
data:
  caster_config.json: |
{{ .Values.config.caster_config_json | indent 4 }}
